### ISSUE TITLE
TODO: Arduino Client

### ISSUE THREAD

**Issue by ckuzma** [ckuzma/pixel-board#1]
- [ ] Determine if NodeMCU can run the board
- [ ] Write initial random-color-generation script
- [ ] Add Alexa on/off capabilities to board
- [ ] Determine if we should use HTTP or MQQT transfer protocol on the NodeMCU
- [ ] Figure out how best to store board maps / instructions
- [ ] Write some basic display routines for Alexa (wake-up, random, text, fire, nighttime)
