### ISSUE TITLE
TODO: Cloud Server

### ISSUE THREAD

**Issue by ckuzma** [ckuzma/pixel-board#2]
- [ ] Write basic FLASK-based Python cloud server
- [ ] Implement proprietary data formatting (if NodeMCU can't handle full JSON objects)
- [ ] Implement REST endpoint for acceptance of images
- [ ] Implement MQTT / HTTP serving of images for NodeMCU
- [ ] Implement REST endpoint for acceptance of videos / routines
