### ISSUE TITLE
TODO: Local Client

### ISSUE THREAD

**Issue by ckuzma** [ckuzma/pixel-board#3]
- [ ] Write method for viewing images stored on the cloud server
- [ ] Write method for uploading a new image to the cloud server
- [ ] Write method for making admin changes to server (image deletion, alteration, etc.)
